version: '3'

services:

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    networks:
      - my-stack-network

  phpmyadmin-service:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql-service
    ports:
      - 8086:80
    networks:
      - my-stack-network
    depends_on:
      - mysql

  web:
    build: .
    ports:
      - 8080:8080
    networks:
      - my-stack-network
    depends_on:
      - mysql

networks:
  my-stack-network:
    driver: bridge