spring:
  datasource:
    driverClassName: ${RDS_DRIVER_DB}
    url: ${DATASOURCE_PROTOCOL}:${DB_TYPE}://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true
springdoc:
  swagger-ui:
    path: /
management:
  endpoints:
    web:
      exposure:
        include: '*'